# .github/actions/setup/action.yaml
name: Set Up Test Environment Action
description: Setup action
runs:
  using: composite
  steps:
    - run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang-12 valgrind
      shell: bash
    - run: |
        echo "Iy" | bash -c 'bash <(curl -s https://raw.githubusercontent.com/tmatis/funcheck/main/scripts/install.sh)'
      shell: bash
    - run: bash --version
      shell: bash
    - run: valgrind --version
      shell: bash
    - run: |
        git clone https://github.com/LeaYeh/42_minishell_tester.git ${{ env.home }}/42_minishell_tester
        chmod +x ${{ env.home }}/42_minishell_tester/tester.sh
        find .github/scripts -type f -name "*.sh" -exec chmod +x {} \;
        cp .github/scripts/*.sh ${{ env.home }}
      shell: bash
