# .github/actions/summary_test_result/action.yaml
name: Test Result Summary Action
description: Compares failed counts between source and target branches
inputs:
  source_failed_count:
    description: Failed count on the source branch
    required: true
  target_failed_count:
    description: Failed count on the target branch
    required: true
runs:
  using: composite
  steps:
    - name: 🆚 Compare failed count
      id: comparison
      run: |
        echo "TARGET_FAILED_COUNT: $TARGET_FAILED_COUNT"
        echo "SOURCE_FAILED_COUNT: $SOURCE_FAILED_COUNT"
        if [ $SOURCE_FAILED_COUNT -gt $TARGET_FAILED_COUNT ]; then
          echo "SOURCE_FAILED_COUNT is greater than TARGET_FAILED_COUNT"
          exit 1
        else
          echo "SOURCE_FAILED_COUNT is less than or equal to TARGET_FAILED_COUNT"
          exit 0
        fi
      env:
        SOURCE_FAILED_COUNT: ${{ inputs.source_failed_count }}
        TARGET_FAILED_COUNT: ${{ inputs.target_failed_count }}
      continue-on-error: true
      shell: bash
    - name: 📈 Show the regressions between source and target branch
      if: steps.comparison.outcome == 'failure'
      run: $HOME/print_changed_test_cases.sh
      shell: bash
    - name: 📉 Show the improvements between source and target branch
      if: steps.comparison.outcome == 'success'
      run: $HOME/print_changed_test_cases.sh || true
      shell: bash
