# .github/actions/summary_test_result/action.yaml
name: Test Result Summary Action
description: Compares failed counts between source and target branches
runs:
  using: composite
  steps:
      # Requires SOURCE_FAILED_COUNT and TARGET_FAILED_COUNT environment variables
    - name: 🆚 Compare failed count
      id: comparison
      run: |
        echo -e "\e[93m🌱 SOURCE_FAILED_COUNT: $SOURCE_FAILED_COUNT\e[0m"
        echo -e "\e[94m🎯 TARGET_FAILED_COUNT: $TARGET_FAILED_COUNT\e[0m"
        if [ $SOURCE_FAILED_COUNT -gt $TARGET_FAILED_COUNT ]; then
          echo -e "\e[1;31mSOURCE_FAILED_COUNT is greater than TARGET_FAILED_COUNT\e[0m"
          exit 1
        else
          echo -e "\e[1;32mSOURCE_FAILED_COUNT is less than or equal to TARGET_FAILED_COUNT\e[0m"
          exit 0
        fi
      continue-on-error: true
      shell: bash
      # Requires TESTER_OUTPUT_DIR environment variable
    - name: 📈 Show the regressions between source and target branch
      if: steps.comparison.outcome == 'failure'
      run: ${{ env.home }}/print_changed_test_cases.sh
      shell: bash
      # Requires TESTER_OUTPUT_DIR environment variable
    - name: 📉 Show the improvements between source and target branch
      if: steps.comparison.outcome == 'success'
      run: ${{ env.home }}/print_changed_test_cases.sh || true
      shell: bash
