# .github/actions/summary_test_result/action.yaml
name: Test Result Summary Action
description: Compares failed counts between source and target branches

inputs:
  source_failed_count:
    description: Number of failed test cases on source branch
    required: true
  target_failed_count:
    description: Number of failed test cases on target branch
    required: true
  source_log_file:
    description: Path to the log file for the source branch
    required: true
  target_log_file:
    description: Path to the log file for the target branch
    required: true
  tester_dir:
    description: Directory containing the tester
    required: true
  tester_output_dir:
    description: Directory containing the tester output files
    required: true
  scripts_dir:
    description: Directory containing the scripts for analyzing the test results
    required: true

runs:
  using: composite
  steps:
    - name: 🆚 Compare failed count
      id: comparison
      env:
        SOURCE_FAILED_COUNT: ${{ inputs.source_failed_count }}
        TARGET_FAILED_COUNT: ${{ inputs.target_failed_count }}
      run: |
        echo -e "\e[93m🌱 SOURCE_FAILED_COUNT: ${{ inputs.source_failed_count }}\e[0m"
        echo -e "\e[94m🎯 TARGET_FAILED_COUNT: ${{ inputs.target_failed_count }}\e[0m"
        if [ ${{ inputs.source_failed_count }} -gt ${{ inputs.target_failed_count }} ]; then
          echo -e "\e[1;31mSOURCE_FAILED_COUNT is greater than TARGET_FAILED_COUNT\e[0m"
          exit 1
        else
          echo -e "\e[1;32mSOURCE_FAILED_COUNT is less than or equal to TARGET_FAILED_COUNT\e[0m"
          exit 0
        fi
      continue-on-error: true
      shell: bash
    - name: 📈 Show the regressions between source and target branch
      if: steps.comparison.outcome == 'failure'
      run: ${{ inputs.scripts_dir }}/print_changed_test_cases.sh
      env:
        TESTER_DIR: ${{ inputs.tester_dir }}
        TESTER_OUTPUT_DIR: ${{ inputs.tester_output_dir }}
        SCRIPTS_DIR: ${{ inputs.scripts_dir }}
      shell: bash
    - name: 📉 Show the improvements between source and target branch
      if: steps.comparison.outcome == 'success'
      run: ${{ inputs.scripts_dir }}/print_changed_test_cases.sh || true
      env:
        TESTER_DIR: ${{ inputs.tester_dir }}
        TESTER_OUTPUT_DIR: ${{ inputs.tester_output_dir }}
        SCRIPTS_DIR: ${{ inputs.scripts_dir }}
      shell: bash
