# .github/workflows/delivery.yaml
name: Continuous Delivery

on:
  push:
    tags:
      - 'v*'

jobs:
  check_tag_version:
    name: Check Tag Version
    runs-on: ubuntu-latest
    outputs:
      main_tag: ${{ steps.check_new_version.outputs.main_tag }}
      is_new_version: ${{ steps.check_new_version.outputs.is_new_version }}
    steps:
    - name: Checkout tag
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check if new version
      id: check_new_version
      run: |
        main_tag=$(git tag --sort=-creatordate --merged origin/main 2>/dev/null | head -n 1) || true
        eval_tag=$(git tag --sort=-creatordate --no-merged origin/main 2>/dev/null | head -n 1) || true
        echo "MAIN_TAG: $main_tag"
        echo "EVAL_TAG: $eval_tag"
        echo "main_tag=$main_tag" >> $GITHUB_OUTPUT
        if [[ "$main_tag" > "$eval_tag" ]]; then
          echo "is_new_version=true" >> $GITHUB_OUTPUT
        else
          echo "is_new_version=false" >> $GITHUB_OUTPUT
        fi

  update_evaluation_branch:
    name: Update Evaluation Branch
    needs: check_tag_version
    if: needs.check_tag_version.outputs.is_new_version == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout tag
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Git
      run: |
        git config --local user.email "lyeh@student.42vienna.com"
        git config --local user.name "Lea Yeh"

    - name: Save .github directory
      run: |
        cp -rf .github ~/.github

    - name: Setup evaluation branch
      run: |
        git checkout -b evaluation origin/evaluation || git checkout -b evaluation
        git merge origin/main || (git checkout --theirs . && git add -A)

    - name: Restore .github directory
      run: |
        rm -rf .github
        mv ~/.github .github

    - name: Partial cleanup of forbidden files
      uses: ./.github/actions/cleanup_partial

    - name: Commit partial cleanup to evaluation branch
      run: |
        git add -A
        git commit -m "[GH-BOT] Remove forbidden files and empty folders"

    - name: 📏 Check norminette
      uses: ./.github/actions/norminette

    - name: Full cleanup of forbidden files
      uses: ./.github/actions/cleanup_full

    - name: Amend full cleanup to evaluation branch
      run: |
        git add -A
        git commit --amend --no-edit

    - name: 🏷️ Set version tag on evaluation branch
      run: |
        eval_tag="${{ needs.check_tag_version.outputs.main_tag }}-eval"
        git tag "$eval_tag"
        git push origin evaluation "$eval_tag"
