# .github/workflows/delivery.yaml
name: Continuous Delivery

on:
  push:
    tags:
      - 'v*'

jobs:
  update_evaluation_branch:
    runs-on: ubuntu-latest
    env:
      proceed:
      main_tag:

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Git
      run: |
        git config --local user.email "lyeh@student.42vienna.com"
        git config --local user.name "Lea Yeh"

    - name: Check tag version
      run: |
        MAIN_TAG=$(git tag --sort=-creatordate --merged origin/main 2>/dev/null | head -n 1) || true
        EVAL_TAG=$(git tag --sort=-creatordate --no-merged origin/main 2>/dev/null | head -n 1) || true
        echo "MAIN_TAG: $MAIN_TAG"
        echo "EVAL_TAG: $EVAL_TAG"
        echo main_tag=$MAIN_TAG >> "$GITHUB_ENV"
        if [[ "$MAIN_TAG" > "$EVAL_TAG" ]]; then
          echo "proceed=true" >> "$GITHUB_ENV"
        else
          echo "proceed=false" >> "$GITHUB_ENV"
        fi

    - name: Setup evaluation branch
      if: env.proceed == 'true'
      run: |
        git checkout -b evaluation origin/evaluation || git checkout -b evaluation
        git merge origin/main || (git checkout --theirs . && git add -A)

    - name: Partial cleanup of forbidden files
      if: env.proceed == 'true'
      uses: ./.github/actions/cleanup_partial

    - name: Commit partial cleanup to evaluation branch
      if: env.proceed == 'true'
      run: |
        git add -A
        git commit -m "[GH-BOT] Remove forbidden files and empty folders"

    - name: 📏 Check norminette
      if: env.proceed == 'true'
      uses: ./.github/actions/norminette

    - name: Full cleanup of forbidden files
      if: env.proceed == 'true'
      uses: ./.github/actions/cleanup_full

    - name: Amend full cleanup to evaluation branch
      if: env.proceed == 'true'
      run: |
        git add -A
        git commit --amend --no-edit

    - name: 🏷️ Set version tag on evaluation branch
      if: env.proceed == 'true'
      run: |
        EVAL_TAG="${{ env.main_tag }}-eval"
        git tag "$EVAL_TAG"
        git push origin evaluation "$EVAL_TAG"
