# .github/workflows/test_workflow.yml
name: Test Workflow

on:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source branch of pull request
        uses: actions/checkout@v4
      - name: Set up build environment
        uses: ./.github/actions/setup

  compilation_test:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout source branch of pull request
        uses: actions/checkout@v4
      - name: Compilation Test
        uses: ./.github/actions/compilation_test

  prepare_test_matrix:
    runs-on: ubuntu-latest
    needs: [setup, compilation_test]
    steps:
      - name: Checkout source branch of pull request
        uses: actions/checkout@v4
      - name: Prepare Test Matrix
        uses: ./.github/actions/prepare_test_matrix
    outputs:
      test_matrix: ${{ steps.prepare_test_matrix.outputs.test_matrix }}
      # TEST_MATRIX: ${{ steps.prepare_test_matrix.outputs.TEST_MATRIX }}

  memory_leak_test:
    runs-on: ubuntu-latest
    needs: prepare_test_matrix
    # strategy:
    #   matrix:
    #     test_script: ${{ fromJson(needs.prepare_test_matrix.outputs.test_matrix) }}
    steps:
      - name: Print Test Matrix 1
        run: echo "Test Matrix Output = ${{ toJson(needs.prepare_test_matrix.outputs) }}"
      - name: Print Test Matrix 2
        run: echo "Test Matrix = ${{ needs.prepare_test_matrix.outputs.test_matrix }}"
      - name: Print TEST_MATRIX
        run: echo "TEST_MATRIX = ${{ needs.prepare_test_matrix.outputs.TEST_MATRIX }}"
    #   - name: Checkout source branch of pull request
    #     uses: actions/checkout@v4
    #   - name: Memory Leak Test
    #     uses: ./.github/actions/memory_leak_test
    #     with:
    #       test_script: ${{ matrix.test_script }}
    # if: ${{ needs.compilation_test.result == 'success' &&
    #       needs.setup.result == 'success' }}

  # mand_regression_test:
  #   runs-on: ubuntu-latest
  #   needs: [setup, compilation_test, memory_leak_test]
  #   steps:
  #     - name: Checkout source branch of pull request
  #       uses: actions/checkout@v4
  #     - name: Mandatory Regression Test
  #       uses: ./.github/actions/mand_regression_test
  #   if: ${{ needs.compilation_test.result == 'success' &&
  #        needs.setup.result == 'success' &&
  #        needs.memory_leak_test.result == 'success' }}
  
  # bonus_regression_test:
  #   extends: ./bonus_regression_test.yml
  #   needs: [setup, compilation_test]
  #   if: ${{ needs.compilation_test.result == 'success' &&
  #         needs.setup.result == 'success' &&
  #         needs.memory_leak_test.result == 'success' }}
